site_name: GPResult
site_url: https://alt-domain.altlinux.team/gpresult
site_author: Maria Alexeeva
site_description: Documentation of GPResult (ALT Linux)

repo_name: gpresult
repo_url: https://altlinux.space/alt-domain/gpresult

theme:
  name: material
  language: ru
  locale: ru
  palette:
    - primary: custom

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: ru
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ru
          default: true
          name: Руский
          build: true
        - locale: en
          name: English
          build: true
  - mike:
      alias_type: redirect
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
