name: Formatting check
on:
  push:

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_formatting:
    runs-on: als-tiny
    container:
      image: registry.altlinux.org/sisyphus/node:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install ruff
        run: apt-get update && apt-get install -y ruff

      - name: Run ruff check
        run: ruff check .

      - name: Run ruff format check
        run: ruff format --check --diff
