site_name: GPResult
site_url: https://alxvmr.gpresult.github.io
site_author: Maria Alexeeva
site_description: Documentation of GPResult (ALT Linux)

theme:
  name: material
  language: ru
  palette:
    - primary: custom

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Русский
      link: /ru/
      lang: ru